#!/usr/bin/env ruby
# frozen_string_literal: true

require "mkmf"
require "rbconfig"
require "rubygems/version"
require_relative "../../lib/pq_crypto/version"

def generate_version_header!
  version = PQCrypto::VERSION
  unless version.match?(/\A[0-9A-Za-z][0-9A-Za-z._+-]*\z/)
    abort "Invalid PQCrypto::VERSION for C header: #{version.inspect}"
  end

  header = File.join(__dir__, "pqcrypto_version.h")
  File.write(header, <<~C)
    /* Generated by extconf.rb from lib/pq_crypto/version.rb. Do not edit. */
    #ifndef PQCRYPTO_VERSION_H
    #define PQCRYPTO_VERSION_H

    #define PQCRYPTO_VERSION #{version.dump}

    #endif
  C
end

generate_version_header!

$CFLAGS << " -std=c11 -Wall -Wextra -O3"
$CFLAGS << " -fstack-protector-strong -D_FORTIFY_SOURCE=2"
$LDFLAGS << " -Wl,-no_warn_duplicate_libraries" if RbConfig::CONFIG["host_os"] =~ /darwin/

VENDOR_ONLY_CFLAGS = "-Wno-unused-parameter -Wno-unused-function -Wno-strict-prototypes -Wno-pedantic -Wno-c23-extensions -Wno-undef"

SANITIZE = ENV["PQCRYPTO_SANITIZE"]
if SANITIZE && !SANITIZE.strip.empty?
  sanitize = SANITIZE.strip
  $CFLAGS.gsub!(/\s-D_FORTIFY_SOURCE=\d+/, "")
  $CFLAGS << " -O1 -g -fno-omit-frame-pointer -fsanitize=#{sanitize}"
  $LDFLAGS << " -fsanitize=#{sanitize}"
end

def host_cpu
  RbConfig::CONFIG.fetch("host_cpu", "")
end

def host_os
  RbConfig::CONFIG.fetch("host_os", "")
end

def aarch64_host?
  host_cpu =~ /\A(?:arm64|aarch64)\z/i
end

def x86_64_host?
  host_cpu =~ /\A(?:x86_64|amd64|x64)\z/i
end

def native_asm_supported_by_default?
  return false if host_os =~ /mswin|mingw|cygwin/i

  aarch64_host?
end

def env_bool(name, default)
  value = ENV[name]
  return default if value.nil? || value.strip.empty? || value.strip.downcase == "auto"

  case value.strip.downcase
  when "1", "true", "yes", "on"
    true
  when "0", "false", "no", "off"
    false
  else
    abort "Invalid #{name}=#{value.inspect}; use 1, 0, true, false, or auto"
  end
end

NATIVE_ASM = env_bool("PQCRYPTO_NATIVE_ASM", native_asm_supported_by_default?)
NATIVE_ARITH = env_bool("PQCRYPTO_NATIVE_ARITH", NATIVE_ASM)
NATIVE_FIPS202 = env_bool("PQCRYPTO_NATIVE_FIPS202", NATIVE_ASM)

X86_VENDOR_ARCH_FLAGS = "-mavx2 -mbmi -mbmi2 -mpopcnt -maes -mssse3 -msse4.1 -msse4.2"

VENDOR_C_ARCH_FLAGS = +""
VENDOR_ASM_ARCH_FLAGS = +""

if x86_64_host? && (NATIVE_ARITH || NATIVE_FIPS202)
  VENDOR_C_ARCH_FLAGS << "#{X86_VENDOR_ARCH_FLAGS} -fno-tree-vectorize"
  VENDOR_ASM_ARCH_FLAGS << X86_VENDOR_ARCH_FLAGS
end

if ENV["PQCRYPTO_NATIVE_TUNE"] == "1"
  VENDOR_C_ARCH_FLAGS << " -march=native -mtune=native"
  VENDOR_ASM_ARCH_FLAGS << " -march=native -mtune=native"
end

def openssl_library_dirs(prefix)
  dirs = [File.join(prefix, "lib64"), File.join(prefix, "lib")]
  dirs.concat(Dir.glob(File.join(prefix, "lib", "*-linux-gnu")))
  dirs.select { |dir| File.directory?(dir) }.uniq
end

def openssl_library_present?(dir, name)
  patterns = [
    "lib#{name}.so",
    "lib#{name}.so.*",
    "lib#{name}.dylib",
    "lib#{name}.*.dylib",
    "lib#{name}.a",
    "lib#{name}.dll.a",
    "#{name}.lib"
  ]

  patterns.any? { |pattern| !Dir.glob(File.join(dir, pattern)).empty? }
end

def openssl_prefix_usable?(prefix)
  return false if prefix.nil?

  prefix = prefix.strip
  return false if prefix.empty?
  return false unless File.exist?(File.join(prefix, "include", "openssl", "opensslv.h"))

  openssl_library_dirs(prefix).any? do |dir|
    openssl_library_present?(dir, "crypto") && openssl_library_present?(dir, "ssl")
  end
end

def explicit_openssl_prefix
  %w[OPENSSL_ROOT_DIR OPENSSL_DIR].each do |var|
    value = ENV[var]
    next if value.nil? || value.strip.empty?

    prefix = File.expand_path(value.strip)
    abort <<~MSG unless openssl_prefix_usable?(prefix)
      #{var}=#{value.inspect} does not point to a complete OpenSSL installation.

      Expected OpenSSL headers under:
        #{File.join(prefix, "include", "openssl")}

      And libcrypto plus libssl under lib, lib64, or a Linux multiarch lib directory.
    MSG

    return prefix
  end

  nil
end

def resolve_openssl_prefix
  explicit = explicit_openssl_prefix
  return explicit if explicit

  candidates = []
  if find_executable("brew")
    %w[openssl@3 openssl].each do |formula|
      prefix = `brew --prefix #{formula} 2>/dev/null`.strip
      candidates << prefix unless prefix.empty?
    end
  end
  candidates.concat(["/opt/homebrew/opt/openssl@3", "/usr/local/opt/openssl@3"])
  candidates.uniq.find { |prefix| openssl_prefix_usable?(prefix) }
end

def pkg_config_value(variable)
  value = `pkg-config --variable=#{variable} openssl 2>/dev/null`.strip
  return nil unless $?.success?
  return nil if value.empty?

  File.expand_path(value)
end

def openssl_pkg_config
  return nil unless find_executable("pkg-config")

  version = `pkg-config --modversion openssl 2>/dev/null`.strip
  return nil unless $?.success?
  return nil if version.empty?
  return { version: version } unless openssl_version_at_least_3?(version)

  incdir = pkg_config_value("includedir")
  libdir = pkg_config_value("libdir")
  return { version: version } unless incdir && libdir
  return { version: version } unless File.exist?(File.join(incdir, "openssl", "opensslv.h"))
  return { version: version } unless openssl_library_present?(libdir, "crypto")
  return { version: version } unless openssl_library_present?(libdir, "ssl")

  { version: version, incdir: incdir, libdir: libdir }
end

def openssl_version_at_least_3?(version)
  Gem::Version.new(version) >= Gem::Version.new("3.0.0")
rescue ArgumentError
  false
end

def configure_openssl_paths(incdir, libdir)
  dir_config("openssl", incdir, libdir)
  $INCFLAGS = "-I#{incdir} #{$INCFLAGS}".strip
  $CPPFLAGS = "-I#{incdir} #{$CPPFLAGS}".strip

  $LIBPATH.delete(libdir)
  $LIBPATH.unshift(libdir)
  $LDFLAGS = "-L#{libdir} #{$LDFLAGS}".strip

  unless host_os =~ /mswin|mingw|cygwin/i || libdir.start_with?("/usr/lib")
    $LDFLAGS = "-Wl,-rpath,#{libdir} #{$LDFLAGS}".strip
  end
end

def configure_compiler_environment
  prefix = resolve_openssl_prefix
  if prefix
    incdir = File.join(prefix, "include")
    libdir = openssl_library_dirs(prefix).find do |dir|
      openssl_library_present?(dir, "crypto") && openssl_library_present?(dir, "ssl")
    end

    configure_openssl_paths(incdir, libdir)
    puts "OpenSSL prefix: #{prefix}"
    puts "OpenSSL include dir: #{incdir}"
    puts "OpenSSL library dir: #{libdir}"
    return
  end

  pkg = openssl_pkg_config
  if pkg && pkg[:incdir] && pkg[:libdir]
    configure_openssl_paths(pkg[:incdir], pkg[:libdir])
    puts "OpenSSL pkg-config: #{pkg[:version]}"
    puts "OpenSSL include dir: #{pkg[:incdir]}"
    puts "OpenSSL library dir: #{pkg[:libdir]}"
    return
  end

  if pkg && pkg[:version]
    if openssl_version_at_least_3?(pkg[:version])
      puts "Ignoring incomplete pkg-config OpenSSL #{pkg[:version]}; headers or libraries were not found"
    else
      puts "Ignoring pkg-config OpenSSL #{pkg[:version]}; OpenSSL 3.0 or later is required"
    end
  else
    puts "OpenSSL pkg-config: unavailable"
  end
  puts "OpenSSL prefix: (none resolved; using compiler defaults)"
end

def native_vendor_sources_for(vendor_dir)
  [
    File.join(vendor_dir, "mlkem-native", "mlkem", "mlkem_native.c"),
    File.join(vendor_dir, "mldsa-native", "mldsa", "mldsa_native.c")
  ]
end

def native_vendor_ready?(vendor_dir)
  File.exist?(File.join(vendor_dir, ".vendored")) &&
    native_vendor_sources_for(vendor_dir).all? { |path| File.exist?(path) }
end

def vendor_script_path
  File.expand_path("../../script/vendor_libs.rb", __dir__)
end

def run_vendor_script!(vendor_dir)
  abort <<~MSG if ENV["PQCRYPTO_AUTO_VENDOR"] != "1"
    PQ Code Package vendored sources are missing.

    Expected:
      #{native_vendor_sources_for(vendor_dir).join("\n  ")}

    The vendor tree is committed to the repository and shipped with the gem.
    If it is missing, the source tree is incomplete or corrupted.

    To fetch upstream sources at the pinned commits run:
      ruby script/vendor_libs.rb

    Or to allow extconf.rb to do this for you set PQCRYPTO_AUTO_VENDOR=1.
  MSG

  script = vendor_script_path
  abort "PQ Code Package vendored sources are missing and script/vendor_libs.rb was not packaged." unless File.exist?(script)

  puts "PQ Code Package native sources are missing; vendoring now (PQCRYPTO_AUTO_VENDOR=1)..."
  ok = system(RbConfig.ruby, script)
  abort <<~MSG unless ok
    Failed to vendor PQ Code Package native sources.

    This build intentionally has no PQClean fallback. Install git/network access or
    vendor mlkem-native and mldsa-native before installing the gem.
  MSG
end

def find_vendor_dir
  candidates = [
    File.join(__dir__, "vendor"),
    File.expand_path("../../ext/pqcrypto/vendor", __dir__),
    File.join(Dir.pwd, "ext", "pqcrypto", "vendor")
  ]

  dir = __dir__
  6.times do
    candidates << File.join(dir, "ext", "pqcrypto", "vendor")
    dir = File.dirname(dir)
  end

  candidates.map! { |path| File.expand_path(path) }
  candidates.uniq!

  primary = File.expand_path(File.join(__dir__, "vendor"))
  run_vendor_script!(primary) unless native_vendor_ready?(primary)

  candidates.find { |path| native_vendor_ready?(path) }
end

def configure_ruby_c_api!
  abort "ruby/thread.h is required" unless have_header("ruby/thread.h")
  abort "rb_thread_call_without_gvl is required" unless have_func("rb_thread_call_without_gvl", "ruby/thread.h")
  abort "rb_nogvl is required" unless have_func("rb_nogvl", "ruby/thread.h")
end

def configure_openssl!
  configure_compiler_environment

  abort "OpenSSL libcrypto is required" unless have_library("crypto")
  abort "OpenSSL libssl is required" unless have_library("ssl")
  abort "openssl/evp.h is required" unless have_header("openssl/evp.h")
  abort "openssl/rand.h is required" unless have_header("openssl/rand.h")
  abort "openssl/crypto.h is required" unless have_header("openssl/crypto.h")
  abort "openssl/x509.h is required" unless have_header("openssl/x509.h")
  abort "openssl/pkcs12.h is required" unless have_header("openssl/pkcs12.h")

  version_check = <<~SRC
    #include <openssl/crypto.h>
    #include <openssl/opensslv.h>
    #if OPENSSL_VERSION_NUMBER < 0x30000000L
    #error "OpenSSL 3.0 or later is required"
    #endif
    int main(void) {
        return (int)OPENSSL_version_major();
    }
  SRC
  abort <<~MSG unless try_link(version_check)
    OpenSSL 3.0 or later is required, but the compiler and linker did not find
    a consistent OpenSSL 3 headers + libcrypto pair. See mkmf.log for the exact
    include paths, library paths, and linker error.

    macOS with Homebrew:
      brew install openssl@3
      OPENSSL_ROOT_DIR="$(brew --prefix openssl@3)" bundle exec rake clean compile

    Debian/Ubuntu:
      sudo apt-get install libssl-dev pkg-config
      pkg-config --modversion openssl   # must report 3.x

    If an old Ruby toolchain injects OpenSSL 1.1 through PKG_CONFIG_PATH,
    point PKG_CONFIG_PATH/PKG_CONFIG_LIBDIR at the system OpenSSL 3 .pc files.
  MSG

  sha3_check = <<~SRC
    #include <openssl/evp.h>
    int main(void) {
        const EVP_MD *md = EVP_sha3_256();
        return md == NULL ? 1 : 0;
    }
  SRC
  abort "OpenSSL SHA3-256 is required (X-Wing combiner)" unless try_link(sha3_check)

  shake_check = <<~SRC
    #include <openssl/evp.h>
    int main(void) {
        const EVP_MD *md = EVP_shake256();
        return md == NULL ? 1 : 0;
    }
  SRC
  abort "OpenSSL SHAKE256 is required (X-Wing key expansion / ML-DSA streaming mu)" unless try_link(shake_check)

  $CFLAGS << " -DHAVE_OPENSSL_EVP_H -DHAVE_OPENSSL_RAND_H"
end

def recursive_include_dirs(root)
  Dir.glob(File.join(root, "**", "*")).select { |p| File.directory?(p) }.map { |p| File.expand_path(p) }
end

def native_vendor_config(vendor_dir)
  abort <<~MSG unless vendor_dir
    PQ Code Package vendored sources are required.

    Expected:
      ext/pqcrypto/vendor/mlkem-native/mlkem/mlkem_native.c
      ext/pqcrypto/vendor/mldsa-native/mldsa/mldsa_native.c

    Run:
      bundle exec rake vendor
  MSG

  mlkem_dir = File.join(vendor_dir, "mlkem-native", "mlkem")
  mldsa_dir = File.join(vendor_dir, "mldsa-native", "mldsa")
  mlkem_c = File.join(mlkem_dir, "mlkem_native.c")
  mldsa_c = File.join(mldsa_dir, "mldsa_native.c")

  missing = [mlkem_c, mldsa_c].reject { |path| File.exist?(path) }
  abort <<~MSG unless missing.empty?
    Missing PQ Code Package native source files:
      #{missing.join("\n  ")}

    This build intentionally has no PQClean fallback. Auto-vendoring did not
    produce the required files. Vendor mlkem-native and mldsa-native, then rebuild.
  MSG

  include_dirs = [__dir__, mlkem_dir, mldsa_dir, *recursive_include_dirs(mlkem_dir), *recursive_include_dirs(mldsa_dir)].uniq
  include_dirs.each { |dir| $CPPFLAGS << " -I#{dir}" }

  {
    mlkem_dir: mlkem_dir,
    mldsa_dir: mldsa_dir,
    mlkem_c: mlkem_c,
    mldsa_c: mldsa_c,
    mlkem_asm: File.join(mlkem_dir, "mlkem_native_asm.S"),
    mldsa_asm: File.join(mldsa_dir, "mldsa_native_asm.S")
  }
end

def native_flags(kind, level, shared:)
  prefix = kind == :mlkem ? "MLK" : "MLD"
  ns = kind == :mlkem ? "pqcr_mlkem" : "pqcr_mldsa"
  flags = []
  flags << "-D#{prefix}_CONFIG_MULTILEVEL_BUILD"
  flags << "-D#{prefix}_CONFIG_PARAMETER_SET=#{level}"
  flags << "-D#{prefix}_CONFIG_NAMESPACE_PREFIX=#{ns}"
  flags << "-D#{prefix}_CONFIG_NO_SUPERCOP"
  flags << (shared ? "-D#{prefix}_CONFIG_MULTILEVEL_WITH_SHARED" : "-D#{prefix}_CONFIG_MULTILEVEL_NO_SHARED")
  flags << "-D#{prefix}_CONFIG_USE_NATIVE_BACKEND_ARITH" if NATIVE_ARITH
  flags << "-D#{prefix}_CONFIG_USE_NATIVE_BACKEND_FIPS202" if NATIVE_FIPS202
  flags.join(" ")
end

def inject_native_sources!(config)
  makefile = File.read("Makefile")

  vendor_objects = []
  build_rules = []

  [
    [:mlkem, "512", config[:mlkem_c], true],
    [:mlkem, "768", config[:mlkem_c], false],
    [:mlkem, "1024", config[:mlkem_c], false],
    [:mldsa, "44", config[:mldsa_c], true],
    [:mldsa, "65", config[:mldsa_c], false],
    [:mldsa, "87", config[:mldsa_c], false]
  ].each do |kind, level, source, shared|
    object = "pqnative_#{kind}_#{level}.o"
    flags = native_flags(kind, level, shared: shared)
    vendor_objects << object
    build_rules << <<~RULE
      #{object}: #{source}
      	$(ECHO) compiling #{source} [#{kind}-#{level}]
      	$(Q) $(CC) $(INCFLAGS) $(CPPFLAGS) $(CFLAGS) $(CCDLFLAGS) #{VENDOR_ONLY_CFLAGS} #{VENDOR_C_ARCH_FLAGS} #{flags} $(COUTFLAG)$@ -c $(CSRCFLAG)$<
    RULE
  end

  if NATIVE_ARITH || NATIVE_FIPS202
    [
      [:mlkem, "512", config[:mlkem_asm], true],
      [:mlkem, "768", config[:mlkem_asm], false],
      [:mlkem, "1024", config[:mlkem_asm], false],
      [:mldsa, "44", config[:mldsa_asm], true],
      [:mldsa, "65", config[:mldsa_asm], false],
      [:mldsa, "87", config[:mldsa_asm], false]
    ].each do |kind, level, source, shared|
      next unless File.exist?(source)

      object = "pqnative_#{kind}_#{level}_asm.o"
      flags = native_flags(kind, level, shared: shared)
      vendor_objects << object
      build_rules << <<~RULE
        #{object}: #{source}
        	$(ECHO) assembling #{source} [#{kind}-#{level}]
        	$(Q) $(CC) $(INCFLAGS) $(CPPFLAGS) $(CFLAGS) $(CCDLFLAGS) #{VENDOR_ONLY_CFLAGS} #{VENDOR_ASM_ARCH_FLAGS} #{flags} $(COUTFLAG)$@ -c $(CSRCFLAG)$<
      RULE
    end
  end

  objects_line = makefile.lines.find { |line| line.start_with?("OBJS = ") }
  raise "Could not find OBJS line in generated Makefile" unless objects_line

  makefile.sub!(objects_line, objects_line.chomp + " #{vendor_objects.join(' ')}\n")

  unless makefile.include?("# vendored pq-code-package objects")
    rules_block = "\n# vendored pq-code-package objects\n" + build_rules.join("\n") + "\n"
    anchor = "$(OBJS): $(HDRS) $(ruby_headers)\n"
    raise "Could not find OBJS dependency anchor in generated Makefile" unless makefile.include?(anchor)

    makefile.sub!(anchor, anchor + rules_block)
  end

  File.write("Makefile", makefile)
end

vendor_dir = find_vendor_dir

puts
puts "=== PQCrypto build configuration ==="
configure_ruby_c_api!
configure_openssl!
native_config = native_vendor_config(vendor_dir)
puts "OpenSSL: system"
puts "ML-KEM: mlkem-native vendored"
puts "ML-DSA: mldsa-native vendored"
puts "Host CPU: #{host_cpu} (#{host_os})"
puts "Native asm auto/forced: #{NATIVE_ASM ? 'enabled' : 'disabled'}"
puts "Native arithmetic backend: #{NATIVE_ARITH ? 'enabled' : 'disabled'}"
puts "Native FIPS202 backend: #{NATIVE_FIPS202 ? 'enabled' : 'disabled'}"
puts "Vendor C arch flags: #{VENDOR_C_ARCH_FLAGS.empty? ? '(none)' : VENDOR_C_ARCH_FLAGS}"
puts "Vendor ASM arch flags: #{VENDOR_ASM_ARCH_FLAGS.empty? ? '(none)' : VENDOR_ASM_ARCH_FLAGS}"
if x86_64_host? && (NATIVE_ARITH || NATIVE_FIPS202)
  puts "x86_64 native backend: AVX2 build flags enabled"
end
puts "PQClean fallback: removed"
puts "Output: pqcrypto/pqcrypto_secure"
puts "===================================="

create_makefile("pqcrypto/pqcrypto_secure")
inject_native_sources!(native_config)
